trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: Print Hello World

# - script: |
#     echo "showing current directory contents"
#     ls
#   displayName: show directory contents

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-keshna'
    organization: '2002-feb24-net'
    scannerMode: 'MSBuild'
    projectKey: '2002-feb24-net_keshna-project1'
    projectName: 'keshna-Project1'

- script: dotnet build
  workingDirectory: Project1
  displayName: dotnet build


- script: dotnet test --logger trx
  workingDirectory: Project1
  displayName: dotnet test


# the default "condition" for every step is "succeeded()" - run this step if the previous step succeeded
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

# this task looks for a zip file and deploys it to azure app service.
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e2856ace-6e0c-471a-af8a-8883735b305d)'
    appType: 'webApp'
    WebAppName: 'CupCakeKesh'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'